# Use the official Node.js image as a base
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --force

# Copy the rest of the application code
COPY . .

# Build the React app
RUN npm run build

# Install a simple server to serve the app
RUN npm install -g serve

# Expose port 3000
EXPOSE 3000

# Command to run the server
CMD ["serve", "-s", "build"]
